### ISSUE TITLE
Get Invoice URL

### ISSUE THREAD

**Issue by kieranheadley** [amochohan/xerolaravel#12]
https://developer.xero.com/documentation/api/invoices/#onlineinvoice

Looking to try and get the online invoice URL using the library you have put together, there was a temporary solution put together in the calcinai/xero library (https://github.com/calcinai/xero-php/issues/173), however I cannot get this to work within Laravel. 

Do you have a solution?

**Comment by amochohan** [comment]
This isn't something i've personally tried so would have to refer you back to the underlying package. I'll leave this issue open in case others can contribute.

**Comment by TakesTheBiscuit** [comment]
Hi there @kieranheadley i don't know if you solved this but i was able to use the same 'temporary solution' they've done over in calcinai/xero-php#173 like so:

In my controller:
```
	public function getInvoice(\Laravel\Lumen\Application $app) {

		$xero = $app->make('XeroPrivate');
		$invoice = $app->make('XeroInvoice');

		$url = new \XeroPHP\Remote\URL($xero, sprintf('%s/%s/OnlineInvoice', $invoice->getResourceURI(), '784b0051-59c5-4735-8478-66fa3e16db66'));
		$request = new \XeroPHP\Remote\Request($xero, $url);
		$request->send();

		$online_invoices = $request->getResponse()->getElements();

		foreach($online_invoices as $invoice){
		    dd($invoice['OnlineInvoiceUrl']);
		}
	}
```

In my `routes.php` file:
```
    $api->get('/xero/show', [
        'as' => 'api.xero.getInvoice',
        'uses' => 'App\Http\Controllers\Controller@getInvoice',
    ]);
```

I hope that helps, using this i was able to generate a public URI like so: `https://in.xero.com/tNgdmcUnkvZg6XlN0PCKj11oI9Q8cZUeXbdlDV7J`

**Comment by sudomoke** [comment]
In case anyone else needs this:

```
public function show($id)
    {

        try {
            $xeroInvoice = XeroPrivate::loadByGUID('Accounting\\Invoice', $id)->getOnlineInvoiceUrl();
            return redirect()->away($xeroInvoice);
        }
        catch(\XeroPHP\Remote\Exception\NotFoundException $e) {
            abort(404);
        }


    }
```
