### ISSUE TITLE
Cannot display product lists using Item

### ISSUE THREAD

**Issue by MattHadfield113** [amochohan/xerolaravel#19]
I have tried every which way i can think of, but i cannot get either a JSON or an Array response from this package, i all i ever seem to get is the headers, but without the actual content, how can i use this to create a foreach for my items in Xero ?

**Comment by tariqbilal** [comment]
You can get the items as:
   $items = XeroPrivate::load('Accounting\\Item')->execute();
   foreach($items as $key => $value)
   {
       echo $value->ItemID;
   }
Hope that helps. The code is tested and works.
