### ISSUE TITLE
Can i use this project for public or partner xero API?

### ISSUE THREAD

**Issue by jaytasol** [amochohan/xerolaravel#3]
Hi,

I want to build application using initially with using Public API and then we will upgrade it for partner API. So is there any way i can use this project for my application? If you can provide some suggestions then it can be great.  

Currently i have setup this and using my public API credentials but it is giving this error 

"Curl error: SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed".

Before i have tried same API credentials in  XeroOAuth-PHP library at that time it was working well and did not giving any certificate error but i think here it is not working as it is public API. 

Thanks,
Jay

**Comment by t2thec** [comment]
I have just had that same issue with the cURL error. Try this: https://github.com/drawmyattention/xerolaravel/issues/1

**Comment by jaytasol** [comment]
Yes Thanks,

But my main concern is can i use this package as public or parter API? How can i achieve that?

**Comment by t2thec** [comment]
Sorry dude, you'll have to wait until the original dev gets back to you on that one. I have only used in as private. The Facades would suggest that you can however.

**Comment by amochohan** [comment]
You are able to use it for public and partner applications as this is effectively just a wrapper for the underlying classes available at calcinai/xero-php to help speed up development with Laravel.

**Comment by jaytasol** [comment]
Thanks for your reply...

Yes, i have seen that, I am trying to use that for my functionality but it is bit confusing, can you help me on this. 

I want to build application which can integrate with different xero account and fetch invoices of them. For this first user need to give us authentication of his/her xero account. I am not sure how i can access authentication functions from calcinai/xero-php. can suggest me any tutorial or can you make me understand how i can implement this?

Thanks,
Jay

**Comment by jaytasol** [comment]
Hi Amo Chohan,

Thanks, I have taken reference from your wrapper(xerolaravel) and make it working. 

Thanks,
Jay
