### ISSUE TITLE
Can't use Facades nor $this->app->make(...)

### ISSUE THREAD

**Issue by ghost** [amochohan/xerolaravel#6]
Hi Amo,

Thanks for the package.
I'm trying to create an invoice without luck.
here are the initial lines that I have:

``` php
$xero = $this->app->make('XeroPrivate');
$invoice = $this->app->make('XeroInvoice');
$xcontact = $this->app->make('XeroContact');
$xcontact->setName($contact->name);
$invoice->setContact($xcontact);
// then foreach(items)
$line1 = $this->app->make('XeroInvoiceLine');
$line1->setDescription($desc);
$line1->setQuantity(1);
$line1->setUnitAmount($price);                      
$line1->setLineAmount($price);
$line1->setLineAmountType('Exclusive');
$line1->setAccountCode('200');
$invoice->addLineItem($line1);
.....

$xero->save($invoice)
```

This is working if that lines are in routes.php ($line1->setLineAmountType('Exclusive'); gives an error though)

However when I move the code to the controller I'm getting Undefined property: App\Http\Controllers\ProjectsController::$app

I've tried 
....

``` php
$xero = new \XeroPrivate;
$invoice = new \XeroInvoice;
$xcontact = new \XeroContact;
```

This time Class 'XeroInvoice' not found
So I thought I should add aliases and added fallowing to the app.php
'XeroInvoice'=> 'DrawMyAttention\XeroLaravel\Facades\XeroInvoice',
'XeroContact'=> 'DrawMyAttention\XeroLaravel\Facades\XeroContact',

Now the error is Class 'DrawMyAttention\XeroLaravel\Facades\XeroContact' not found

So I've created the Facade manually like:

``` php
namespace DrawMyAttention\XeroLaravel\Facades;

use Illuminate\Support\Facades\Facade;

class XeroContact extends Facade
{
    protected static function getFacadeAccessor() { return 'XeroContact'; }
}
```

Now the error is Call to undefined method DrawMyAttention\XeroLaravel\Facades\XeroContact::setName()

I'm not very familiar with Facades, IOC and ServiceProviders.

My laravel version is "laravel/framework": "5.1.*"

Thanks in advance.

**Comment by ghost** [comment]
Probably not a good solution but I've managed to make it work.

``` php
    $config = 'xero/config.php';
    $configPath = config_path($config);
    $config = include $configPath;
    $xero = new \XeroPHP\Application\PrivateApplication($config);
    $invoice= new \XeroPHP\Models\Accounting\Invoice();
    $xcontact= new \XeroPHP\Models\Accounting\Contact();
```

**Comment by ncatanchin** [comment]
I'm a Laravel newbie - also can't seem to use `$this->app('make')`. Using Laravel 5.

I've been able to get it to work with:

``` php
$xero = App::make('XeroPublic');
$invoice = App::make('XeroInvoice');
```

and so on but would be good to get clarity. Probably need to learn more about Laravel :)

**Comment by wisoot** [comment]
@iaroel Have you register provider into your app config? You need that in order to use facade.
Also you can't app()->make() facade, facade has been made already.
You can however, resolve the class with app()->make(). e.g. app()->make('XeroPHP\Application\PrivateApplication');

**Comment by ghost** [comment]
@wisoot Yep I've registered the provider:

```
    'providers' => [
    .......
    'DrawMyAttention\XeroLaravel\Providers\XeroServiceProvider',
    ......
```

and 

```
    'aliases' => [
    .......
    'XeroPrivate'=> 'DrawMyAttention\XeroLaravel\Facades\XeroPrivate',
    'XeroInvoice'=> 'DrawMyAttention\XeroLaravel\Facades\XeroInvoice',
    'XeroContact'=> 'DrawMyAttention\XeroLaravel\Facades\XeroContact',
    ......




```
